Algoritmo "AreaTrapezio"
//calcula a area do trapezio
// Autor: Victor Leinad
// Data atual  : 08/03/2021
Var
base, altura,area,basemaior:real
Inicio
escreval("digite a base do trapezio:")
leia(base)
escreval("digite a altura maior do trapezio:")
leia(basemaior)
escreval("digite a altura do trapezio:")
leia(altura)

area <- base*altura*basemaior

escreval("a area do trapezio e:",area,"m2")
Fimalgoritmo