Algoritmo "ConversãoDeTemperatura"
// 
//  
// Descrição   : converte graus celsius em fahrenheit
// Autor(a)    : Victor Leinad da Silva Ramos
// Data atual  : 16/03/2021
Var

fahrenheit,celsius:real

Inicio

//Entrada
escreval("Quanto ta a temperatura em graus celsius: ")
leia(celsius)

//Processamento
 fahrenheit <- ( celsius × 9/5) + 32

 //Saida
escreval(celsius"o celsius, convertido em fahrenheit ficara: ")


Fimalgoritmo